# Generated by Django 3.1.6 on 2021-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('bytecode', models.TextField()),
                ('abi', models.TextField()),
                ('tx_hash', models.TextField(null=True)),
                ('tx_receipt', models.TextField(null=True)),
                ('deployed', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
